connections.max = 50
bind.host = 0.0.0.0
bind.port.min = 4401
bind.port.max = 4410

startup.delay = 3
heartbeat = 20

dm.api.version = 1.0.0.0
dm.name = Aadhaar Device Manager (multiplatform)
dm.vendor = UIDAI
dm.version = 1.2.1
